### PR TITLE
New taskbar icon library

### LINKED ISSUE #70: App hangs after RDP connection
The app just completely freezes after connecting to RDP session. I cannot interact with window or system tray icon and numlock layer is blinking. Killing process and starting again fixes the issue.
### Reproduction steps
1. Start Aurora on PC1
2. Connect to PC1 from PC2 via RDP
3. Disconnect and get back to PC1

### Frequency
Every time

### Aurora Version:
v59

### Previously an Issue?
Not sure, but i think yes

Logs:
```[INFO] 16:31:34: 
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 24
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: v59
========================================
 
[INFO] 16:31:34: Loading devices from assembly... 
[INFO] 16:31:34: [ASUS] Could not find Asus Aura SDK, please install version v1.07.71 
[INFO] 16:31:34: Loading Configuration 
[INFO] 16:31:34: Loading Plugins 
[INFO] 16:31:34: Loading KB Layouts 
[INFO] 16:31:34: Loading Input Hooking 
[INFO] 16:31:34: Loading RazerSdkManager 
[WARN] 16:31:34: Currently installed razer sdk version "0.0.0" is not supported by the RazerSdkManager! 
[INFO] 16:31:34: Loading Applications 
[INFO] 16:31:37: Fetching latest pointers 
[INFO] 16:31:37: Loading Device Manager 
[INFO] 16:31:37: [Device][Logitech] Trying to initialize Logitech using the dll for GHUB 
[INFO] 16:31:37: [Device][Logitech] Initialized Successfully. 
[INFO] 16:31:37: [Device][Wooting] Initialized Successfully. 
[INFO] 16:31:37: Starting GameStateListener 
[INFO] 16:31:37: Listening for game integration calls... 
[INFO] 16:31:37: Loading ResourceDictionaries... 
[INFO] 16:31:37: [IPCServer] Pipe created 44736323 
[INFO] 16:31:37: [AuroraCommandsServerIPC] Pipe created 5828284 
[INFO] 16:31:37: Loaded ResourceDictionaries 
[INFO] 16:31:37: Loading ConfigUI... 
[WARN] 16:31:38: Could not find an AutoNode getter method for field '_ParsedData' of type 'JObject'. It will not be automatically populated. 
```

### PR DESCRIPTION
**Pull request by voed**
Fixes #70 

**This pull request proposes the following changes:**

- Updated taskbar icon library

### CODE REVIEW

**Comment by Aytackydln** [comment]
Seems to work on .Net 4.8 but not on 6.0 sadly

**Comment by voed** [comment]
> Seems to work on .Net 4.8 but not on 6.0 sadly

Tried on your master branch, works fine too.
https://github.com/voed/Aurora/tree/master

**Comment by Aytackydln** [comment]
Okay I will check it out tomorrow

**Comment by Aytackydln** [comment]
can you do a pull from master or reimplement the new library again? I still coudln't make it work

**Comment by voed** [comment]
I have tried to reproduce your issue on 3 different devices with windows 10 and 11, but everything works fine.

**Comment by Aytackydln** [comment]
Is this still a problem for you? I've changed the library a while ago

**Comment by Aytackydln** [comment]
Alright, closing this then

**Pull request closed without merging**
