### PR TITLE
add support for keychron q1 knob ansi

### PR DESCRIPTION
**Pull request by tirrorex**

### CODE REVIEW

**Comment by tirrorex** [comment]
should be fine now if you don't cancel the build :D

**Comment by Aytackydln** [comment]
https://github.com/Aurora-RGB/Aurora/releases/tag/v9
heres your build :) it will be in the full release once sleep-from-wake issue is solved

**Comment by tirrorex** [comment]
Awesome ! Thank you

Thibaut NOAH iOS developer

________________________________

**Comment by tirrorex** [comment]
Screenshot 2022-02-02 060901

Actually there seems to be a few things to fix in ansi layout, which is weird considering that was the one i used to compile.
I see keys that i removed inside the layout.

**Comment by tirrorex** [comment]
Missing _ansi in the KeyboardLayoutManager.cs :(
Must have forgotten to save the file before commiting.

**Comment by Aytackydln** [comment]
Okay, can you pull from dev again and make PR again?

**Comment by tirrorex** [comment]
Already done ;)

Le mer. 2 févr. 2022 à 16:08, Aytaç Kayadelen ***@***.***> a
écrit :

**Pull request merged**
