### PR TITLE
Updated Dota 2 items layer

### PR DESCRIPTION
**Pull request by Crapy**
This updates the Dota 2 items layer to the new layout including backpack and changing the number of items in stash

### CODE REVIEW

**Comment by Aytackydln** [comment]
Nice, another dota player :) While you're at it, can you also remove the line below? This has bad behavior on custom games.

Dota2AbilityLayerHandler.cs:
if (ability.IsUltimate)
    key = Properties.AbilityKeys[5];

**Comment by Crapy** [comment]
> Nice, another dota player :) While you're at it, can you also remove the line below? This has bad behavior on custom games.
> 
> Dota2AbilityLayerHandler.cs: if (ability.IsUltimate) key = Properties.AbilityKeys[5];

I haven't tested it but i'll take your word for it, any way to reproduce the error/problem you experience?

**Comment by Aytackydln** [comment]
In games like Custom Hero Chaos, you can have multiple Ultimate abilities and their locations might be different. With that line all ultimates are considered to be on key "R"

**Comment by Crapy** [comment]
> In games like Custom Hero Chaos, you can have multiple Ultimate abilities and their locations might be different. With that line all ultimates are considered to be on key "R"

I've changed it as you requested hopefully it doesn't break normal games and works normally with ultimates

**Comment by Aytackydln** [comment]
Don't worry, it is like that in my own fork

**Comment by Aytackydln** [comment]
Nice, I'm merging this, btw I also recommend my own fork. It has much faster animations but doesnt have fps speed so I didn't merge it here yet.

**Pull request merged**
