### PR TITLE
Create keychron_q1_knob.json

### PR DESCRIPTION
**Pull request by tirrorex**
Create the layout so the keyboard can be supported by aurora when plugged with openrgb

### CODE REVIEW

**Comment by tirrorex** [comment]
So the layout should be added with this?
Not sure if i missed something about the mapping for openrgb.
I assumed the ig is the "tag" and since all keys seems to be mapped properly in OpenRGBKeyNames.cs there shouldn't be anymore to do.

**Comment by Aytackydln** [comment]
Yes, it seems right. You need to tell if it is working or not, since you have the keyboard with that layout. I'm assuming you can't compile? If so, you can change the layout json file with any other layout then you can check if it is working

**Comment by tirrorex** [comment]
I mean, i can compile but i would need a how-to as i never worked with c# before.
I can see an iss file in the installer folder but my google search tells me i should be creating it not using it, kinda lost right now

**Comment by Aytackydln** [comment]
iss is for installer. If you are using Visual Studio or rider, make Aurora default project then you can click the "start" button above to launch directly from IDE

**Comment by tirrorex** [comment]
I am using visual studio code.
I ran the project with visual studio 2022 but it tells me i have to run a NuGet package restore to generate project.assets.json in colorbox folder.

**Comment by tirrorex** [comment]
Moved to vs 2019 as it seems it was an issue with that.
New error 👍 
Aurora-LightFXWrapper.vcxproj(27,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.

Is that a package issue?

**Comment by Aytackydln** [comment]
image
click "Retarget Solution" like this then apply

**Comment by tirrorex** [comment]
Can't seem to amend my commits, not used to git on windows, is it possible to squash them during the merge ?
Everything working fine locally :)

**Comment by Aytackydln** [comment]
Sorry, I don't know much about git :D I will review then merge when I have free time, tho :)

**Comment by tirrorex** [comment]
Okay, i managed to do it with the commande line, sourcetree and github desktop gave me cancer lol.
Unfortunatly i had to force push but it now appears as one commit, it will be easier for you to see the changes.
Also i noticed i modified the layout_ansi in one of my commits so this change was reverted :)
The commit history should now be clean with a single commit to add the support for my keyboard

**Comment by Aytackydln** [comment]
can you remove .idea folder from your PR?

**Comment by tirrorex** [comment]
Should be fine now

**Comment by Aytackydln** [comment]
layout in my pc looks like this :D 
image

**Comment by tirrorex** [comment]
The \\ key is missing. Weird
Also the spacing is broken somehow :/
Screenshot 2022-02-01 203252

**Comment by tirrorex** [comment]
Oh i see, You have the second layer for the bottom keys (< instead of , for example)

**Comment by Aytackydln** [comment]
Yes, only works with US layout. Okay then, you can name your layout US only :D

**Comment by Aytackydln** [comment]
Well, I merged this but I cancelled the build. Can you make another pr to dev branch?

**Pull request merged**
